name = "udp-socket-service"
service_scheme = "https"
service_host = "localhost"
# service_host = "plaza.local"
service_port = 28200
connect_timeout = 3 # seconds
logging_config = "config/console.yaml"
apikey = "3678fde6af84c28f93667fd9623ae6df"
session = "jtEw7eepufhKWhc6"
